name 'mwser-shib-oauth2-bridge'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures mwser-shib-oauth2-bridge'
long_description 'Installs/Configures mwser-shib-oauth2-bridge'
version '0.1.1'

depends 'mysql'
depends 'mysql2_chef_gem'
depends 'database'
depends 'shib-oauth2-bridge'
